# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Araştırma Adı')),
                ('active', models.BooleanField(default=False, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Araştırma',
                'verbose_name_plural': 'Araştırmalar',
            },
        ),
    ]
