# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=40, verbose_name='Başlık')),
                ('soru', models.TextField(blank=True, null=True, verbose_name='Soru')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Sorulma Tarihi')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Survey', verbose_name='Araştırma')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
            },
        ),
    ]
