# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_soru'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
