# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import election.profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-Posta')),
                ('is_active', models.BooleanField(default=False, verbose_name='E-posta Onayı?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ('created_at',),
            },
            managers=[
                ('objects', election.profile.models.UserProfileManager()),
            ],
        ),
    ]
