# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180129_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Şehir')),
                ('code', models.CharField(max_length=3, verbose_name='Plaka')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='UserTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='İlçe')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.UserCity', verbose_name='Şehir')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.UserTown', verbose_name='İlçe'),
        ),
    ]
