# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180130_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertown',
            options={'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.UserTown', verbose_name='İlçeler'),
        ),
        migrations.AlterField(
            model_name='usertown',
            name='name',
            field=models.CharField(max_length=60, verbose_name='İlçeler'),
        ),
    ]
